{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "helloenv.fullname" . }}-pdb
  labels:
    {{- include "helloenv.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helloenv.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}